apiVersion: v1
kind: Service
metadata:
  name: lb-client
spec:
  selector:
    app: defibrillator-client
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: defibrillator-client
spec:
  selector:
    matchLabels:
      app: defibrillator-client
  template:
    metadata:
      labels:
        app: defibrillator-client
    spec:
      containers:
      - name: defibrillator-client
        image: rborovets/defibrillator-client:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80
